Development setup

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -178,3 +178,70 @@ tasks:
         else
           echo "Open in browser: $URL"
         fi
+
+  backend:api-key:create:
+    desc: Create backend API key
+    silent: true
+    cmds:
+      - |
+        NGINX_PORT=$(docker compose port nginx 80 | cut -d: -f2)
+        if [ -z "$NGINX_PORT" ]; then
+          echo "✗ Services not running (run: docker compose up --detach)"
+          exit 1
+        fi
+        TOKEN=$(curl -s -X POST "http://localhost:${NGINX_PORT}/api/v1/auth/login" \
+          -H "Content-Type: application/json" \
+          -d '{"username":"global-admin@os2iot.dk","password":"hunter2"}' | jq -r '.accessToken')
+        if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
+          echo "✗ Failed to login - ensure services are running"
+          exit 1
+        fi
+        RESULT=$(curl -s -X POST "http://localhost:${NGINX_PORT}/api/v1/api-key" \
+          -H "Authorization: Bearer $TOKEN" \
+          -H "Content-Type: application/json" \
+          -d '{"name":"test-development", "expiresOn": "2100-01-01T00:00:00Z", "permissionIds": [ 2 ]}')
+        if echo "$RESULT" | grep -q '"key"'; then
+          API_KEY=$(echo "$RESULT" | jq --raw-output '.key')
+          echo "✓ API key:"
+          echo
+          echo "$API_KEY"
+        else
+          echo "Error creating API key: $RESULT"
+        fi
+
+  dev:start:
+    desc: Start containers in development mode
+    cmds:
+      - task: dev:compose
+        vars:
+          TASK_ARGS: up --build --detach --wait
+
+  dev:stop:
+    desc: Stop containers in development mode
+    cmds:
+      - task: dev:compose
+        vars:
+          TASK_ARGS: stop
+
+  dev:status:
+    desc: Show status of development containers
+    cmds:
+        # We use `printf` to escape having Task processing the placeholders.
+        - docker compose --file docker-compose.development.yml ps os2iot-frontend  os2iot-backend --format '{{printf "{{.Image}} {{.State}}\t{{.Status}}"}}'
+
+  dev:log:
+    desc: "Follow development container log; examples: `task {{.TASK}} SERVICE=frontend` or `task {{.TASK}} --interactive`"
+    # https://taskfile.dev/blog/if-and-variable-prompt#prompt-for-required-variables
+    requires:
+      vars:
+        - name: SERVICE
+          enum: [frontend, backend]
+    cmds:
+      - task: dev:compose
+        vars:
+          TASK_ARGS: logs --follow os2iot-{{.SERVICE}}
+
+  dev:compose:
+    desc: Start containers in development mode
+    cmds:
+      - docker compose --file docker-compose.development.yml {{.TASK_ARGS}} {{.CLI_ARGS}}
